### ISSUE TITLE
Question about output of model scaled yolo v4 ?

### ISSUE THREAD

**Issue by deeplearningbygit** [Chen-MingChang/pytorch_YOLO_OpenVINO_demo#1]
Hello,

Thank for your excellent repo. I have tested with yolo v5 and it works perfect. But as a newbie I don't know how  to determine the layer for output with scaled yolo v4, and yolo v4 like you did with yolo v5 (Conv_245,Conv_261,Conv_277). Can you show me the guide to do it so I can convert these model with openvino ? 
Thank a lot !

**Comment by Chen-MingChang** [comment]
Hi,
You can use "Netron" tool to open *.onnx to find out the output nodes.
Or you can refer to the configuration file I provided for accuracy cheker tool at pytorch_YOLO_OpenVINO_demo/configs.
For example, you can check "accuracy-check-scaled-yolov4-p5.yml" to know the outputs of scaled-yolov4-p5 are Conv_698, Conv_714, Conv_730.

**Comment by Chen-MingChang** [comment]
> Hello,
> 
> Thank for your excellent repo. I have tested with yolo v5 and it works perfect. But as a newbie I don't know how to determine the layer for output with scaled yolo v4, and yolo v4 like you did with yolo v5 (Conv_245,Conv_261,Conv_277). Can you show me the guide to do it so I can convert these model with openvino ?
> Thank a lot !

Hi,
You can use "Netron" tool to open *.onnx to find out the output nodes.
Or you can refer to the configuration file I provided for accuracy cheker tool at pytorch_YOLO_OpenVINO_demo/configs.
For example, you can check "accuracy-check-scaled-yolov4-p5.yml" to know the outputs of scaled-yolov4-p5 are Conv_698, Conv_714, Conv_730.

**Comment by deeplearningbygit** [comment]
Thank a lot for your help !
