### ISSUE TITLE
ValueError: too many values to unpack (expected 4)

### ISSUE THREAD

**Issue by zengqingfa** [Chen-MingChang/pytorch_YOLO_OpenVINO_demo#2]
I trained a model on the colab , reference this tutorial: 
`https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data`. 

It is then converted to IR models (best.xml and best.bin). 
![image](https://user-images.githubusercontent.com/39977054/123073831-5b09c480-d449-11eb-9afb-c216b731398b.png)

Then copyed the repository, place my model in the image tag above, and run `python yolo__openvino_demo.py-m best.xml-i images/ dryer_179.jpg-at yolov5-d CPU`.
![image](https://user-images.githubusercontent.com/39977054/123073955-7aa0ed00-d449-11eb-851e-a57584d48273.png)
![image](https://user-images.githubusercontent.com/39977054/123074203-ade37c00-d449-11eb-9806-86897dc709a3.png)

 Why did it go wrong?

**output:**
```
(tf_cpu) C:\Users\Tenbay\Desktop\pytorch_YOLO_OpenVINO_demo-main\pytorch_YOLO_OpenVINO_demo-main>python yolo__openvino_demo.py -m best.xml -i images/dryer_179.jpg -at yolov5 -d CPU
C:\Program Files (x86)\Intel\openvino_2021.3.394\python\python3.7\ngraph\utils\types.py:37: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  (NgraphType.boolean, np.bool),
[ INFO ] Creating Inference Engine...
[ INFO ] Loading network files:
        best.xml
        best.bin
yolo__openvino_demo.py:255: DeprecationWarning: Reading network using constructor is deprecated. Please, use IECore.read_network() method instead
  net = IENetwork(model=model_xml, weights=model_bin)
[ INFO ] Preparing inputs
yolo__openvino_demo.py:272: DeprecationWarning: 'inputs' property of IENetwork class is deprecated. To access DataPtrs user need to use 'input_data' property of InputInfoPtr objects which can be accessed by 'input_info' property.
  input_blob = next(iter(net.inputs))
MFX: Unsupported extension: images/dryer_179.jpg
[ INFO ] Loading model to the plugin
[ INFO ] Starting inference...
To close the application, press 'CTRL+C' here or switch to the output window and press ESC key
To switch between sync/async modes, press TAB key in the output window
yolo__openvino_demo.py:356: DeprecationWarning: 'outputs' property of InferRequest is deprecated. Please instead use 'output_blobs' property.
  output = exec_net.requests[cur_request_id].outputs
Traceback (most recent call last):
  File "yolo__openvino_demo.py", line 447, in <module>
    sys.exit(main() or 0)
  File "yolo__openvino_demo.py", line 368, in main
    args.prob_threshold, args.architecture_type)
  File "yolo__openvino_demo.py", line 171, in parse_yolo_region
    out_blob_n, out_blob_c, out_blob_h, out_blob_w = blob.shape
ValueError: too many values to unpack (expected 4)
```
Anyone can help me?

**Comment by Chen-MingChang** [comment]
@zengqingfa 
Not sure what steps did to do to convert your model.
After training, you should get a *.pt model. 
And then first use "export.py" in my repository to convert *.pt into *.onnx.
In second step is to run "mo.py" to *.xml.
If so, you may run the demo successfully.

**Comment by cmdjzs** [comment]
@zengqingfa 
Hi,Have you solved this issue?I met this problem yesterday,and currently its useful.
while transforming onnx to IR format, the context of output should be Conv_551,Conv_503,Conv_455,but my order of layers is Conv_455,Conv_503,Conv_551 at the begining,reorder the layers,its work.

**Comment by zengqingfa** [comment]
Thank you. I have solved the issue. @Chen-MingChang @cmdjzs

**Comment by first-wording** [comment]
> Thank you. I have solved the issue. @Chen-MingChang @cmdjzs

你好，我也遇到了同样的问题，请问你是怎么解决的？

**Comment by zengqingfa** [comment]
我的是因为onnx转IR模型的时候 没按教程写这几个参数(类似这个几个)
![image](https://user-images.githubusercontent.com/39977054/126613443-84bacef3-d3ec-47d9-bbde-e3b60607f5fb.png)

这个几个参数的获取办法：

下个这个
![image](https://user-images.githubusercontent.com/39977054/126612159-9ddce3b9-a2a5-4785-bd2c-de5956e21f46.png)

然后双击你yolo导出的onnx模型 会用Netron打开那个模型 然后ctrl + f   输入 Transpose

![image](https://user-images.githubusercontent.com/39977054/126612812-2d936af6-3c5f-4300-a36a-a76848067771.png)

单击 它上面那个Conv，记下名字 有三个

@first-wording

**Comment by first-wording** [comment]
> 我的是因为onnx转IR模型的时候 没按教程写这几个参数(类似这个几个)
> ![image](https://user-images.githubusercontent.com/39977054/126613443-84bacef3-d3ec-47d9-bbde-e3b60607f5fb.png)
> 
> 这个几个参数的获取办法：
> 
> 下个这个
> ![image](https://user-images.githubusercontent.com/39977054/126612159-9ddce3b9-a2a5-4785-bd2c-de5956e21f46.png)
> 
> 然后双击你yolo导出的onnx模型 会用Netron打开那个模型 然后ctrl + f 输入 Transpose
> 
> ![image](https://user-images.githubusercontent.com/39977054/126612812-2d936af6-3c5f-4300-a36a-a76848067771.png)
> 
> 单击 它上面那个Conv，记下名字 有三个
> 
> @first-wording

好的，我测试一下，感谢

**Comment by first-wording** [comment]
> 我是因为onnx转IR模型的时候没按教程写这几个参数（类似这个几个）
> ![图像](https://user-images.githubusercontent.com/39977054/126613443-84bacef3-d3ec-47d9-bbde-e3b60607f5fb.png)
> 
> 这几个参数的获取方法：
> 
> 下个这个
> ![图像](https://user-images.githubusercontent.com/39977054/126612159-9ddce3b9-a2a5-4785-bd2c-de5956e21f46.png)
> 
> 然后双击你yolo导出的onnx模型会用Netron打开那个模型然后ctrl + f输入Transpose
> 
> ![图像](https://user-images.githubusercontent.com/39977054/126612812-2d936af6-3c5f-4300-a36a-a76848067771.png)
> 
> 单个它上面那个那个Conv，记下名字有三个
> 
> @第一个措辞

好的，我测试一下，感谢，方便加个微信么？1850061652

**Comment by zengqingfa** [comment]
@first-wording 算了 我是菜鸡 只跑过一个模型

**Comment by first-wording** [comment]
> @first-wording 算了 我是菜鸡 只跑过一个模型
没事，根据你刚刚说的，我那个问题已经解决了，再次感谢
