### ISSUE TITLE
兄弟，怎么设置信度？

### ISSUE THREAD

**Issue by zengqingfa** [Chen-MingChang/pytorch_YOLO_OpenVINO_demo#5]
![image](https://user-images.githubusercontent.com/39977054/123917976-f8b74380-d9b5-11eb-90c4-94b514ca9ff6.png)
是哪个？上面的还是下面的？

**Comment by zengqingfa** [comment]
@Chen-MingChang

**Comment by Chen-MingChang** [comment]
@zengqingfa 
-t 是偵測物件的門檻值
-iout 是關係到 nms 運算後保留的 roi 數量
我想你需要的是 -t

**Comment by zengqingfa** [comment]
嗯嗯 是 谢谢 @Chen-MingChang
