### ISSUE TITLE
Question about command to generate the IR of YOLOv5 model ?

### ISSUE THREAD

**Issue by hoangkhoiLE** [Chen-MingChang/pytorch_YOLO_OpenVINO_demo#7]
Dear @Chen-MingChang,

Thank for your excellent work. I got a question about this comand:
````
python3 /opt/intel/openvino_2021.1.110/deployment_tools/model_optimizer/mo.py  --input_model yolov5s.onnx -s 255 --reverse_input_channels --output Conv_245,Conv_261,Conv_277
```
with the argument -s 255, we must scale the image: input will be divided by this value. But I don't see in the demo code you do that . Is there something wrong with it ? Please explain me ! Thank you in advance !

Best regard !

**Comment by Chen-MingChang** [comment]
> Dear @Chen-MingChang,
> 
> Thank for your excellent work. I got a question about this comand:
> 
> ```
> python3 /opt/intel/openvino_2021.1.110/deployment_tools/model_optimizer/mo.py  --input_model yolov5s.onnx -s 255 --reverse_input_channels --output Conv_245,Conv_261,Conv_277
> ```
> with the argument -s 255, we must scale the image: input will be divided by this value. But I don't see in the demo code you do that . Is there something wrong with it ? Please explain me ! Thank you in advance !
> 
> Best regard !
> ```

Hi, @hoangkhoiLE

In OpenVINO converter with the argument -s 255, computing of scaling will be included in the model converted by openVINO.

Therefore, the input does not need to do scaling again in demo.

**Comment by hoangkhoiLE** [comment]
Thank you for your kind response !
